/** Dados mock da Caixa de Entrada (substituir por API no futuro) */

export const mockEmails = [
  {
    id: '1',
    from: 'joao.silva@email.com',
    to: 'contato@contaux.com.br',
    subject: 'Documentos para declaração de IRPF 2025',
    body: 'Olá, segue em anexo os documentos para a declaração do IRPF deste ano.\n\nPreciso que verifiquem se está tudo correto.\n\nAtenciosamente,\nJoão Silva',
    receivedAt: '2026-10-07T14:30:00Z',
    read: false,
    starred: true,
    folder: 'inbox',
  },
  {
    id: '2',
    from: 'tech.solutions@empresa.com.br',
    to: 'contato@contaux.com.br',
    subject: 'Re: Fatura de serviços contábeis - Outubro',
    body: 'Recebemos a fatura NF-2024-005. O pagamento será feito via PIX até o vencimento.\n\nAbraço,\nEquipe Tech Solutions',
    receivedAt: '2026-10-07T10:15:00Z',
    read: false,
    starred: false,
    folder: 'inbox',
  },
  {
    id: '3',
    from: 'receita@sefaz.gov.br',
    to: 'contato@contaux.com.br',
    subject: 'Lembrete: Entrega da DCTF - Outubro/2026',
    body: 'Prezado contribuinte,\n\nLembramos que o prazo para entrega da DCTF referente ao mês de outubro se encerra em 15/10.\n\nAtenciosamente,\nSEFAZ',
    receivedAt: '2026-10-06T16:00:00Z',
    read: true,
    starred: false,
    folder: 'inbox',
  },
  {
    id: '4',
    from: 'maria.fernanda@email.com',
    to: 'contato@contaux.com.br',
    subject: 'Dúvida sobre planejamento tributário',
    body: 'Boa tarde,\n\nGostaria de agendar uma reunião para discutir estratégias de planejamento tributário para minha empresa.\n\nQual a disponibilidade de vocês?\n\nObrigada,\nMaria Fernanda',
    receivedAt: '2026-10-05T09:45:00Z',
    read: true,
    starred: true,
    folder: 'inbox',
  },
  {
    id: '5',
    from: 'contato@contaux.com.br',
    to: 'joao.silva@email.com',
    subject: 'Confirmação de recebimento de documentos',
    body: 'Olá João,\n\nConfirmamos o recebimento dos seus documentos para a declaração do IRPF.\n\nEntraremos em contato em breve com o prazo de conclusão.\n\nAtenciosamente,\nEquipe Contaux',
    receivedAt: '2026-10-07T15:00:00Z',
    read: true,
    starred: false,
    folder: 'sent',
  },
]
